server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/static/, file:C:/project/upload/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
mybatis:
  type-aliases-package: com.example.demo.vo
  mapper-locations: classpath:/mappers/**/*.xml

kakao:
  client_id: 79f2a3a73883a82595a2202187f96cc5
  redirect_uri: http://localhost:8080/login/oauth2/code/kakao

custom:
  uploadDirPath: C:/project/upload